import type { LevelDef } from "./engine";

/**
 * Fifteen boards, easiest first. Mechanics arrive one at a time: open plates,
 * switches and bridges, fragile tiles, toggles, corridors that force parity
 * planning, heavy switches, and finally everything together.
 * scripts/solve-levels.ts checks every board and prints its shortest solution.
 */
export const LEVELS: LevelDef[] = [
  {
    name: "Warm-up",
    hint: "Arrows or WASD roll the block. Stand it upright on the green tile.",
    map: [
      ".#####.",
      ".#S###.",
      ".#####.",
      ".#####.",
      ".###G#.",
      ".#####.",
    ],
  },
  {
    name: "The bend",
    hint: "A corridor one tile wide only lets you roll along it.",
    map: [
      "###.....",
      "#S#.....",
      "###.....",
      ".#......",
      ".#......",
      ".#####..",
      ".###G#..",
      ".#####..",
    ],
  },
  {
    name: "Two keys",
    hint: "Round switches react to any touch. Each one opens half of the gap.",
    map: [
      "...###...",
      "...#S#...",
      "...###...",
      "....#....",
      "....#....",
      "..#####..",
      "..c###d..",
      "..#####..",
      "....3....",
      "....4....",
      "...###...",
      "...###...",
      "...#G#...",
    ],
    switches: {
      c: { kind: "soft", action: "open", bridges: ["3"] },
      d: { kind: "soft", action: "open", bridges: ["4"] },
    },
  },
  {
    name: "Glass ring",
    hint: "Pale tiles crack under a standing block. Lie across them instead.",
    map: [
      "...####.......",
      "...#S##.......",
      "...####.......",
      "....oo........",
      "....oo........",
      "..ooo#ooo.....",
      "..o#####o.....",
      "..o#####o.....",
      "..ooo#ooo.....",
      "....oo........",
      "....oo........",
      "...####.......",
      "...#G##.......",
      "...####.......",
    ],
  },
  {
    name: "Toggle",
    hint: "This switch flips both bridges: one closes, one opens.",
    map: [
      "###.....",
      "#S#.....",
      "###.....",
      ".#......",
      ".1......",
      ".###....",
      ".#b#....",
      ".###....",
      "...2....",
      "...2....",
      "...###..",
      "...##G..",
      "...###..",
    ],
    switches: {
      b: { kind: "soft", action: "toggle", bridges: ["1","2"] },
    },
    bridges: {"1": true, "2": false},
  },
  {
    name: "Thin ice",
    hint: "A long stretch of fragile tiles. Get flat before you enter.",
    map: [
      "..####......",
      "..#S##......",
      "..####......",
      "...oo.......",
      "...oo.......",
      "...oo.......",
      "...oo.......",
      "..####......",
      "..##G#......",
      "..####......",
    ],
  },
  {
    name: "The switch",
    hint: "One switch, one bridge, and the whole walk back.",
    map: [
      "###.........",
      "#S#.........",
      "###.........",
      ".#..........",
      ".#..........",
      ".####11###..",
      ".#.....###..",
      ".###...#G#..",
      ".#a#...###..",
      ".###........",
    ],
    switches: {
      a: { kind: "soft", action: "open", bridges: ["1"] },
    },
  },
  {
    name: "Stepping stones",
    hint: "Solid tiles are exactly where you need to stand. Nowhere else.",
    map: [
      "####........",
      "#S##........",
      "####........",
      ".o..........",
      ".o..........",
      ".#oo#oo#....",
      ".......o....",
      ".......o....",
      ".......#oo#.",
      "..........o.",
      "..........o.",
      ".........###",
      ".........G##",
      ".........###",
    ],
  },
  {
    name: "Corridors",
    hint: "Corners must be reached standing. Count your steps.",
    map: [
      "####..........",
      "#S##..........",
      "####..........",
      ".#............",
      ".#............",
      ".#######......",
      ".......#......",
      ".......#......",
      ".......#####..",
      ".........###..",
      ".........#G#..",
      ".........###..",
    ],
  },
  {
    name: "Long way round",
    hint: "No tricks, just a lot of corners.",
    map: [
      "####.....",
      "#S##.....",
      "####.....",
      ".#.......",
      ".#.......",
      ".#.......",
      "###......",
      "###......",
      "#####....",
      "....#....",
      "....#....",
      "....####.",
      ".......#.",
      ".......#.",
      "....####.",
      "....#....",
      "....#....",
      "....###..",
      "....###..",
      "....##G..",
      "....###..",
    ],
  },
  {
    name: "Heavy",
    hint: "An X switch only reacts to the block standing upright on it.",
    map: [
      "####.........",
      "#S##.........",
      "####.........",
      ".#...........",
      ".#...........",
      ".####........",
      "....#........",
      "....#........",
      "..#####......",
      "..##A##......",
      "..#####......",
      "....#........",
      "....#........",
      "....###33####",
      "..........##G",
      "..........###",
    ],
    switches: {
      a: { kind: "heavy", action: "open", bridges: ["3"] },
    },
  },
  {
    name: "Standing room",
    hint: "Reach the X switch upright without touching the pale tiles.",
    map: [
      "..#####.....",
      "..##S##.....",
      "..#####.....",
      "..#####.....",
      "....#.......",
      "..ooooo.....",
      "..o#A#o.....",
      "..ooooo..###",
      "....#....##G",
      "....###55###",
      ".........###",
    ],
    switches: {
      a: { kind: "heavy", action: "open", bridges: ["5"] },
    },
  },
  {
    name: "Locksmith",
    hint: "A soft switch, then a heavy one. Order matters.",
    map: [
      "####...........",
      "#S##...........",
      "####...........",
      ".#.............",
      ".#.............",
      ".####..........",
      "....#..........",
      "....#..........",
      "..#####7#####..",
      "..#g###.##B##..",
      "..#####.#####..",
      "............8..",
      "............8..",
      "...........###.",
      "...........G##.",
      "...........###.",
    ],
    switches: {
      g: { kind: "soft", action: "open", bridges: ["7"] },
      b: { kind: "heavy", action: "open", bridges: ["8"] },
    },
  },
  {
    name: "Glass maze",
    hint: "Almost everything cracks. Roll flat and think ahead.",
    map: [
      "###...........",
      "#S#...........",
      "###...........",
      ".oo...........",
      ".oo...........",
      ".oo...........",
      "###...........",
      "###...........",
      "###oo###......",
      "###oo###......",
      ".....###......",
      "......oo......",
      "......oo......",
      "......oo......",
      ".....####.....",
      ".....####.....",
      ".....####oo###",
      "...........###",
      "...........#G#",
      "...........###",
    ],
  },
  {
    name: "Homecoming",
    hint: "Everything you learned, in one board. Welcome home.",
    map: [
      "####.............",
      "#S##.............",
      "####.............",
      ".#.###...........",
      ".#.###...........",
      ".#####...........",
      "....oo...........",
      "....oo...........",
      "....oo...........",
      "...#####.........",
      "...##h##99#......",
      "...#####..#......",
      "..........#......",
      ".........###.....",
      ".........###..###",
      ".........#B#88###",
      ".........###..##G",
      "..............###",
    ],
    switches: {
      h: { kind: "soft", action: "open", bridges: ["9"] },
      b: { kind: "heavy", action: "open", bridges: ["8"] },
    },
  },
];
